### ISSUE TITLE
only header, no content

### ISSUE THREAD

**Issue by gamer321lol** [floatzeI/2016-roblox#3] opened 2022-01-25 08:11 UTC
and it doesnt work

**Comment by floatzeI** [comment] 2022-01-28 01:04
Unfortunately the asset redirect feature seems to break often, I think that might be the cause. I added a flag to disable it - pull the repo again, and run ```node util/flag assetRedirectsEnabled disable``` and let me know if the pages load after that.

**Comment by gamer321lol** [comment] 2022-01-29 07:53
also by header i mean the topbar

**Comment by gamer321lol** [comment] 2022-01-29 07:53
shouldve been more specific

**Comment by gamer321lol** [comment] 2022-01-29 08:01
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "authorization"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:256:14)
    at Object.request (node:https:353:10)
    at dispatchHttpRequest (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\axios\lib\adapters\http.js:202:25)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\axios\lib\adapters\http.js:46:10)
    at dispatchRequest (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\axios\lib\core\dispatchRequest.js:53:10)
    at Axios.request (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\axios\lib\core\Axios.js:108:15)
    at Function.wrap [as request] (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\axios\lib\helpers\bind.js:9:15
)
    at actualHandler (C:\Users\Jacob\Downloads\2016-roblox-main\.next\server\pages\api\proxy.js:163:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}

**Comment by floatzeI** [comment] 2022-01-29 17:38
The error "invalid value undefined" should be fixed now.

The issue where only the top bar is visible might be specific to the home page (since it doesn't exist yet). Other pages should work, but the home page specifically is just blank right now.

**Comment by gamer321lol** [comment] 2022-01-30 05:43
the games page is also blank

**Comment by gamer321lol** [comment] 2022-01-30 05:43
buuttt thats prob fixed

**Comment by gamer321lol** [comment] 2022-01-30 05:49
You must pass the robot test before logging in.

**Comment by gamer321lol** [comment] 2022-01-30 05:52
TypeError: selected.element is not a function
    at CreationsTab (C:\Users\Jacob\Downloads\2016-roblox-main\.next\server\pages\develop.js:1077:36)
    at d (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:3
3:498)
    at bb (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:
36:16)
    at a.b.render (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production
.min.js:42:43)
    at a.b.read (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.m
in.js:41:83)
    at Object.exports.renderToString (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-ser
ver.node.production.min.js:52:138)
    at renderPage (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\Jacob\Downloads\2016-roblox-main\.next\server\pages\_document.js:33:30)
    at Object.defaultGetInitialProps (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\next\dist\server\render.js:
316:51)
    at Function.getInitialProps (C:\Users\Jacob\Downloads\2016-roblox-main\.next\server\chunks\6859.js:515:20)

**Comment by floatzeI** [comment] 2022-02-08 16:48
> You must pass the robot test before logging in.

More details at #10. This will be fixed once #5 is added.

**Comment by floatzeI** [comment] 2022-02-08 16:48
> TypeError: selected.element is not a function at CreationsTab (C:\Users\Jacob\Downloads\2016-roblox-main.next\server\pages\develop.js:1077:36) at d (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:3 3:498) at bb (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.min.js: 36:16) at a.b.render (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production .min.js:42:43) at a.b.read (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-server.node.production.m in.js:41:83) at Object.exports.renderToString (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\react-dom\cjs\react-dom-ser ver.node.production.min.js:52:138) at renderPage (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\next\dist\server\render.js:686:46) at Object.ctx.renderPage (C:\Users\Jacob\Downloads\2016-roblox-main.next\server\pages_document.js:33:30) at Object.defaultGetInitialProps (C:\Users\Jacob\Downloads\2016-roblox-main\node_modules\next\dist\server\render.js: 316:51) at Function.getInitialProps (C:\Users\Jacob\Downloads\2016-roblox-main.next\server\chunks\6859.js:515:20)

A lot of pages give weird errors if you aren't logged in. These will hopefully be fixed soon, so that they redirect you if you aren't logged in.

**Closed** 2022-03-15 20:26 UTC
